### PR TITLE
Add anonymous connection to SMTP relay

### PR DESCRIPTION
**Pull request by thbar**
Some SMTP servers only allow anonymous connections. This makes sure I can connect to those.

### CODE REVIEW

**Comment by Yannik** [comment]
As open relays are a major spam issue, and therefore pretty much extinct (or blacklisted), I don't see any incentive on including these here, unless you can provide some very good reasons for supporting this.

**Comment by thbar** [comment]
It's for a non-public (internal) SMTP server, which I don't manage myself (unfortunately, otherwise I wouldn't have had to issue that PR) & which will remain un-authentified for the future.

I definitely understand your point (it's the same as mine, actually). I can manage that in my fork if you're not willing to merge that in.

**Comment by Yannik** [comment]
IMO internal SMTP servers should require authentication as well, otherwise any rogue machine (or user) in the internal network can go wild. Feel free to keep that in a fork, but I wouldn't like it in the master branch. Maybe you can convince the maintainer of that server to leave the past behind and implement authentication some day ;-) (Otherwise, perhaps use a different server for your outgoing mail?)

**Comment by thbar** [comment]
I definitely agree that internal SMTP servers without auth are a massive trouble waiting to happen. I already made that argument, and will push your own words in addition to that.

I'm not happy keeping this into master either - I'll just keep a fork for now.

Thanks for your comments!

**Comment by thbar** [comment]
@Yannik thanks to your recent words + extra pushing on my side, the maintainer of the server accepted to provide a secure connector instead. So: thank you!

**Comment by Yannik** [comment]
@thbar Glad to hear! It's always good to push back on security issues like this.

**Pull request closed without merging**
